import './Confetti.scss'

const Confetti = () => {
	return (
		<main>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
			<div className="firework"></div>
		</main>
	)
}

export default Confetti
