export { ReactComponent as SquareCheck } from './squareCheck.svg'
export { ReactComponent as Picture } from './pictureImage.svg'
export { ReactComponent as Calendar } from './calendarImage.svg'
export { ReactComponent as LeftArrow } from './calendarImage.svg'
export { ReactComponent as RightArrow } from './calendarImage.svg'
